[package]
name = "nottes-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = {  version = "4.5.41", features = ["derive"]}
rusqlite = { version =  "0.37.0", features = ["bundled"]}
shellexpand = "3.1.1"
ratatui = "0.29.0"
crossterm = "0.28.1"
